# Generated by Django 4.2.5 on 2023-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting1', models.CharField(max_length=50)),
                ('greeting2', models.CharField(max_length=50)),
                ('my_name', models.CharField(max_length=50)),
                ('my_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
