# Generated by Django 4.2.5 on 2023-10-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_describe_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_icon', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
