# Generated by Django 4.2.5 on 2024-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
